In [1]:
print("hello diving into pytorch")

hello diving into pytorch


In [3]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))


2.5.1+cu121
True
NVIDIA GeForce RTX 3050 Laptop GPU


In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to tensors 

In [7]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [17]:
vector = torch.tensor([[7,7],[2,3]])
vector

tensor([[7, 7],
        [2, 3]])

In [19]:
vector.ndim

2

In [25]:
vector.shape


torch.Size([2, 2])

In [29]:
matrix = torch.tensor([[7,8],[3,4],[4,6]])
matrix

tensor([[7, 8],
        [3, 4],
        [4, 6]])

In [31]:
matrix.ndim

2

In [33]:
matrix[0]

tensor([7, 8])

In [37]:
matrix.shape

torch.Size([3, 2])

In [47]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,6,8],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 8],
         [2, 4, 5]]])

In [49]:
TENSOR.ndim

3

In [51]:
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
# Create random tensors

In [55]:
rt = torch.rand(3,4)
rt

tensor([[0.5224, 0.3515, 0.8606, 0.3491],
        [0.6415, 0.4769, 0.5711, 0.6657],
        [0.1358, 0.0847, 0.3982, 0.4762]])

In [57]:
rt.ndim

2

In [59]:
rt.shape

torch.Size([3, 4])

In [65]:
rt2 = torch.rand(10,10,10)
rt2


tensor([[[8.5967e-01, 6.3690e-01, 9.7880e-01, 7.0451e-01, 6.2570e-01,
          7.4171e-01, 6.8073e-01, 5.7449e-02, 9.2080e-01, 2.0610e-01],
         [5.9140e-02, 2.2135e-01, 6.5978e-01, 9.6463e-01, 1.6276e-01,
          5.7841e-01, 9.4064e-01, 8.3143e-01, 9.6000e-02, 4.7224e-01],
         [6.5473e-01, 8.1305e-01, 2.6530e-04, 1.1005e-01, 7.6564e-01,
          5.9732e-01, 1.6934e-01, 5.7764e-01, 7.4191e-01, 4.3667e-01],
         [2.9676e-01, 9.9500e-01, 2.1341e-01, 9.5209e-01, 7.7246e-01,
          4.5820e-01, 5.4318e-01, 4.3588e-01, 2.9060e-02, 5.2659e-01],
         [7.0229e-01, 6.7448e-01, 1.1467e-01, 5.5091e-01, 4.0326e-01,
          2.1484e-01, 3.4968e-01, 1.1695e-01, 8.3481e-01, 1.1815e-01],
         [1.0004e-01, 1.9875e-01, 3.0649e-01, 3.9898e-01, 5.0634e-01,
          3.7750e-01, 7.9693e-01, 1.8546e-01, 6.4440e-01, 8.5783e-01],
         [4.3573e-01, 2.7115e-01, 9.5786e-01, 5.3750e-02, 6.2062e-01,
          2.8587e-01, 2.0695e-01, 6.9797e-01, 6.7420e-01, 7.8362e-01],
         [8.2

In [67]:
rt2.ndim

3

In [69]:
rt2.shape

torch.Size([10, 10, 10])

In [71]:
# create a randome tensor eith similat shape to an image tensor

In [73]:
rist = torch.rand(size=(224,224,3))
rist.shape, rist.ndim

(torch.Size([224, 224, 3]), 3)

In [75]:
#zeros and ones

In [81]:
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [83]:
zero * rt

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [87]:
zero.dtype

torch.float32

In [93]:
ones = torch.ones(3,4)
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [95]:
# creating range of tensors and tensors-like

In [105]:
r = torch.arange(0,10)

In [103]:
# tensors like

In [109]:
tl = torch.zeros_like(input=r)
tl

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [111]:
tl2 = torch.ones_like(input=r)
tl2

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])