In [5]:
import torch
print(torch.__version__)



2.5.1+cu121


In [7]:
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
xrs = x.reshape(1,9)

In [11]:
xrs = x.reshape(1,9)
xrs

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [13]:
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [15]:
s = torch.stack([x,x,x,x], dim=1)
s

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [17]:
sq = torch.squeeze(x)
sq

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
usq = torch.unsqueeze(x, dim)


NameError: name 'dim' is not defined